# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
  pipelines:
    - pipeline: buildContosoAir # identifier for the resource using in pipeline resource variables
      source: mpieler1.ContosoAir # name of the pipeline that produces and artifiact
      trigger:
        branches:
         include:
           - master
pool:
  vmImage: ubuntu-latest

steps:

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
